// <auto-generated />
using System;
using EasyHotelSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyHotelSystem.Migrations
{
    [DbContext(typeof(EasyHotelSystemContext))]
    [Migration("20191107145613_Reserva")]
    partial class Reserva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyHotelSystem.Models.Employee", b =>
                {
                    b.Property<long>("CpfFunc")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DtAdmissao");

                    b.Property<DateTime>("DtNasc");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("Telefone");

                    b.HasKey("CpfFunc");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Escorts", b =>
                {
                    b.Property<long>("CpfAcom")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long>("Celular");

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasMaxLength(10);

                    b.Property<long>("CpfHos");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Nascim");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Rg");

                    b.Property<int>("Telefone");

                    b.HasKey("CpfAcom");

                    b.ToTable("Escorts");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Guest", b =>
                {
                    b.Property<long>("CpfHos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long>("Celular");

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasMaxLength(10);

                    b.Property<long>("CpfAcomp");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Nascim");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Rg");

                    b.Property<int>("Telefone");

                    b.HasKey("CpfHos");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Payment", b =>
                {
                    b.Property<int>("CodPagamento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CpfFunc");

                    b.Property<long>("CpfHos");

                    b.Property<DateTime>("DataCheckin");

                    b.Property<DateTime>("DataCheckout");

                    b.Property<string>("FormaPag")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("HrCheckin");

                    b.Property<DateTime>("HrCheckout");

                    b.Property<string>("NomeHos")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NumQuarto")
                        .HasMaxLength(4);

                    b.Property<int>("QtdAdu");

                    b.Property<int>("QtdCriancas");

                    b.Property<decimal>("Taxa");

                    b.Property<string>("TipoQuarto")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<decimal>("Valor");

                    b.HasKey("CodPagamento");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Reserva", b =>
                {
                    b.Property<int>("CodReserva")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CpfFunc");

                    b.Property<long>("CpfHos");

                    b.Property<DateTime>("DataCheckin");

                    b.Property<DateTime>("DataCheckout");

                    b.Property<string>("NomeHos");

                    b.Property<int>("NumQuarto");

                    b.Property<int>("QtdAcomp");

                    b.HasKey("CodReserva");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Room", b =>
                {
                    b.Property<int>("NumQuarto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodReserva");

                    b.Property<string>("DescQuarto")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("StatusQuarto")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<decimal>("ValorDiaria");

                    b.HasKey("NumQuarto");

                    b.ToTable("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
