// <auto-generated />
using System;
using EasyHotelSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyHotelSystem.Migrations
{
    [DbContext(typeof(EasyHotelSystemContext))]
    [Migration("20191108191744_RoomReserva")]
    partial class RoomReserva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyHotelSystem.Models.Employee", b =>
                {
                    b.Property<long>("CpfFunc")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DtAdmissao");

                    b.Property<DateTime>("DtNasc");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("Telefone");

                    b.HasKey("CpfFunc");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.EmployeePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FuncID");

                    b.Property<int>("PagID");

                    b.Property<int?>("PagamentoCodPagamento");

                    b.Property<long?>("RecepcionistaCpfFunc");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoCodPagamento");

                    b.HasIndex("RecepcionistaCpfFunc");

                    b.ToTable("EmployeePayment");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.EmployeeReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FuncID");

                    b.Property<long?>("RecepcionistaCpfFunc");

                    b.Property<int>("ResID");

                    b.Property<int?>("ReservasCodReserva");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionistaCpfFunc");

                    b.HasIndex("ReservasCodReserva");

                    b.ToTable("EmployeeReserva");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Escorts", b =>
                {
                    b.Property<long>("CpfAcom")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long>("Celular");

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasMaxLength(10);

                    b.Property<long>("CpfHos");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Nascim");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Rg");

                    b.Property<int>("Telefone");

                    b.HasKey("CpfAcom");

                    b.HasIndex("CpfHos");

                    b.ToTable("Escorts");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Guest", b =>
                {
                    b.Property<long>("CpfHos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long>("Celular");

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Complemento")
                        .HasMaxLength(10);

                    b.Property<long>("CpfAcomp");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Nascim");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Rg");

                    b.Property<int>("Telefone");

                    b.HasKey("CpfHos");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Payment", b =>
                {
                    b.Property<int>("CodPagamento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CpfFunc");

                    b.Property<long>("CpfHos");

                    b.Property<DateTime>("DataCheckin");

                    b.Property<DateTime>("DataCheckout");

                    b.Property<string>("FormaPag")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("HrCheckin");

                    b.Property<DateTime>("HrCheckout");

                    b.Property<string>("NomeHos")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NumQuarto")
                        .HasMaxLength(4);

                    b.Property<int>("QtdAdu");

                    b.Property<int>("QtdCriancas");

                    b.Property<decimal>("Taxa");

                    b.Property<string>("TipoQuarto")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<decimal>("Valor");

                    b.HasKey("CodPagamento");

                    b.HasIndex("CpfHos");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Reserva", b =>
                {
                    b.Property<int>("CodReserva")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CpfFunc");

                    b.Property<long>("CpfHos");

                    b.Property<DateTime>("DataCheckin");

                    b.Property<DateTime>("DataCheckout");

                    b.Property<string>("NomeHos")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NumQuarto");

                    b.Property<int>("QtdAcomp");

                    b.HasKey("CodReserva");

                    b.HasIndex("NumQuarto");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Room", b =>
                {
                    b.Property<int>("NumQuarto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodReserva");

                    b.Property<string>("DescQuarto")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("StatusQuarto")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<decimal>("ValorDiaria");

                    b.HasKey("NumQuarto");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.RoomReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QuarID");

                    b.Property<int?>("QuartoNumQuarto");

                    b.Property<int>("ResID");

                    b.Property<int?>("ReservasCodReserva");

                    b.HasKey("Id");

                    b.HasIndex("QuartoNumQuarto");

                    b.HasIndex("ReservasCodReserva");

                    b.ToTable("RoomReserva");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.EmployeePayment", b =>
                {
                    b.HasOne("EasyHotelSystem.Models.Payment", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoCodPagamento");

                    b.HasOne("EasyHotelSystem.Models.Employee", "Recepcionista")
                        .WithMany("ListaChecksRealizados")
                        .HasForeignKey("RecepcionistaCpfFunc");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.EmployeeReserva", b =>
                {
                    b.HasOne("EasyHotelSystem.Models.Employee", "Recepcionista")
                        .WithMany("ListaReservas")
                        .HasForeignKey("RecepcionistaCpfFunc");

                    b.HasOne("EasyHotelSystem.Models.Reserva", "Reservas")
                        .WithMany()
                        .HasForeignKey("ReservasCodReserva");
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Escorts", b =>
                {
                    b.HasOne("EasyHotelSystem.Models.Guest")
                        .WithMany("ListaAcompanhantes")
                        .HasForeignKey("CpfHos")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Payment", b =>
                {
                    b.HasOne("EasyHotelSystem.Models.Guest")
                        .WithMany("ListaPagamentos")
                        .HasForeignKey("CpfHos")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EasyHotelSystem.Models.Reserva", b =>
                {
                    b.HasOne("EasyHotelSystem.Models.Room")
                        .WithMany("ListaReservas")
                        .HasForeignKey("NumQuarto")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EasyHotelSystem.Models.RoomReserva", b =>
                {
                    b.HasOne("EasyHotelSystem.Models.Room", "Quarto")
                        .WithMany()
                        .HasForeignKey("QuartoNumQuarto");

                    b.HasOne("EasyHotelSystem.Models.Reserva", "Reservas")
                        .WithMany()
                        .HasForeignKey("ReservasCodReserva");
                });
#pragma warning restore 612, 618
        }
    }
}
